### ISSUE TITLE
create flist for odoo 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/flist-builder-config#1]
we need to create flist for odoo ( our running odoos ), it will contains ```odoo and postgresql as a 
database```

and create a startup toml file for restoring of database it will take database name 

we will connect it with restic to take periodic backup from it

**Comment by Dina-Abd-Elrahman** [comment]
- installed odoo in container locally 
got alot of errors 
trying to solve them.

**Comment by Dina-Abd-Elrahman** [comment]
- an error while trying to install postgresql database on ubuntu 18.04 

```
postgres@Ubuntu:~$ psql
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

error is gone by restarting the postgresql service.

**Comment by Dina-Abd-Elrahman** [comment]
- fixed packages dependencies, trying to make odoo service start on container

**Comment by Dina-Abd-Elrahman** [comment]
- i'm done with installation of odoo , now odoo v8 is installed on container on ```cario-office``` farm. 

- testing it with our database now , export and dump the database to see if it will work correctly or not.

**Comment by Dina-Abd-Elrahman** [comment]
- I'm done with freeflow flist & startup.toml file, testing it now with new fixes in startup toml file.

**Comment by PeterNashaat** [comment]
- odoo flists created 

https://hub.grid.tf/nashaatp/codescalers_odoo.flist.md

https://hub.grid.tf/nashaatp/odoo_bettertoken.flist.md

https://hub.grid.tf/nashaatp/odoo_bvba.flist.md

https://hub.grid.tf/nashaatp/odoo_7star.flist.md
